INSERT INTO `pays` (`id`, `nom`, `abrev`, `ordre`) VALUES
(1, 'FRANCE', 'FR', 1),
(2, 'BELGIQUE', 'BE', 2),
(3, 'ITALIE', 'IT', 3),
(4, 'ESPAGNE', 'ES', 4),
(5, 'LUXEMBOURG', 'LU', 5),
(6, 'ALLEMAGNE', 'DE', 6),
(7, 'HOLLANDE', 'NL', 7),
(8, 'DANEMARK', 'DK', 8),
(9, 'POLOGNE', 'PL', 9),
(10, 'ROUMANIE', 'RO', 10),
(11, 'REPUBLIQUE TCHEQUE', 'CZ', 11),
(12, 'CEE', 'CE', 12),
(13, 'USA', 'US', 13),
(14, 'ANGLETERRE', 'UK', 14),
(15, 'LITUANIE', 'LT', 15),
(16, 'SUISSE', 'CH', 16);
