twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
      google_maps_key: '%google_maps_key%'

when@test:
    twig:
        strict_variables: true

